baseURL = "http://localhost:1313"
title = "Mark Hannel"
theme = "blowfish"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

[outputs]
  home = ["HTML", "RSS", "JSON"] 