baseURL = "http://localhost:1313"
title = "Mark Hannel"
theme = "blowfish"
defaultContentLanguage = "en"

enableRobotsTXT = true

[module]
  hugoVersion = "0.143.0"

[pagination]
  pagerSize = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"] 